<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<!DOCTYPE html><html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>เพิ่มทันตแพทย์ | SmileCare</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="${pageContext.request.contextPath}/css/clinic.css?v=12" rel="stylesheet"><script src="${pageContext.request.contextPath}/js/admin-staff.js?v=2" defer></script></head>
<body class="bg-light"><%@ include file="includes/clinic-userbar.jspf" %><main class="container py-5"><div class="card shadow-sm p-4 mx-auto" style="max-width:680px"><h1 class="h3 mb-1">เพิ่มทันตแพทย์</h1><p class="text-secondary mb-4">กรอกข้อมูลบัญชีและข้อมูลติดต่อของทันตแพทย์</p><form action="${pageContext.request.contextPath}/admin/dentists" method="post" data-staff-form novalidate>
  <label class="form-label" for="username">ชื่อผู้ใช้</label><input id="username" class="form-control mb-3" name="username" placeholder="เช่น Dentist1" pattern="[A-Za-z0-9]{4,8}" minlength="4" maxlength="8" autocomplete="off" required>
  <label class="form-label" for="password">รหัสผ่าน</label><input id="password" class="form-control mb-3" name="password" type="password" placeholder="เช่น Dentist#1" pattern="[A-Za-z0-9!#_.]{8,16}" minlength="8" maxlength="16" autocomplete="new-password" required>
  <label class="form-label" for="firstName">ชื่อ</label><input id="firstName" class="form-control mb-3" name="firstName" placeholder="เช่น สมชาย" pattern="[A-Za-zก-ฮะ-ฺเ-๎]{2,20}" minlength="2" maxlength="20" required>
  <label class="form-label" for="lastName">นามสกุล</label><input id="lastName" class="form-control mb-3" name="lastName" placeholder="เช่น ทันตสุข" pattern="[A-Za-zก-ฮะ-ฺเ-๎]{2,20}" minlength="2" maxlength="20" required>
  <label class="form-label" for="phone">เบอร์โทรศัพท์</label><input id="phone" class="form-control mb-3" name="phone" type="tel" placeholder="เช่น 0812345678" inputmode="numeric" pattern="[0-9]{10}" minlength="10" maxlength="10" required>
  <label class="form-label" for="email">อีเมล</label><input id="email" class="form-control mb-4" name="email" type="email" placeholder="เช่น dentist@example.com" minlength="5" maxlength="60" required>
  <button class="btn btn-primary" type="submit">บันทึกทันตแพทย์</button><a class="btn btn-link" href="${pageContext.request.contextPath}/admin/staff">กลับ</a>
</form></div></main></body></html>
